/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bite_Ride;


import io.github.cdimascio.dotenv.Dotenv;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author job parado
 */
public class SettingsPage extends javax.swing.JFrame {
    
    boolean condition;
    /**
     * Creates new form SettingsPage
     */
    public SettingsPage() {
        initComponents();
    }
    
    Dotenv dotenv = Dotenv.load();
    String url = dotenv.get("Database_URL");
    String user = dotenv.get("Admin_Name");
    String pass = dotenv.get("Admin_Password");

    private String phoneNumber,firstname,surname,password,role;

    // one setter for account
    public void SetAccount(String phoneNumber,String firstname , String surname,String password) {
        this.phoneNumber=phoneNumber;
        this.firstname=firstname;
        this.surname=surname;
        this.password=password;
    }
    
    private String hashPassword(String password) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashed = md.digest(password.getBytes());
        StringBuilder sb = new StringBuilder();
        for (byte b : hashed) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    } catch (NoSuchAlgorithmException e) {
        return password;
    }
    }

    public void setPassword(String password) {
        this.password = password;
    }
    public String getPassword() {
        return password;
    }
    public void setRole(String role) {
        this.role=role;
        btnApplyAsMerchant.setEnabled(false);
        btnApplyAsDriver.setEnabled(false);
    }

    // display for  account information
    public void DisplayAccountInformation() {
        txtPhoneNumber.setText(phoneNumber);
        txtFirstName.setText(firstname);
        txtSurName.setText(surname);
        txtPassword.setText(password);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        black = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        settings = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        accountInformation = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtFirstName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        btnShowPassword = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtInfoPassword = new javax.swing.JLabel();
        btnUpdatePassword = new javax.swing.JButton();
        btnEnableShowPassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSurName = new javax.swing.JTextField();
        Support = new javax.swing.JPanel();
        btnGiveFeedBack = new javax.swing.JButton();
        btnApplyAsDriver = new javax.swing.JButton();
        btnApplyAsMerchant = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Settings Page");
        setResizable(false);

        black.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        settings.setBackground(new java.awt.Color(255, 255, 255));

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogOut.setText("Log out");
        btnLogOut.setFocusable(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setFocusable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingsLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Settings", settings);

        accountInformation.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Firstname:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Phone Number:");

        txtPassword.setEditable(false);
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        txtFirstName.setEditable(false);
        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPhoneNumber.setEditable(false);
        txtPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnShowPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnShowPassword.setText("Show Password");
        btnShowPassword.setContentAreaFilled(false);
        btnShowPassword.setEnabled(false);
        btnShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPasswordActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userIcon.png"))); // NOI18N

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Confirm Changes");
        btnUpdate.setEnabled(false);
        btnUpdate.setFocusable(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtInfoPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtInfoPassword.setForeground(new java.awt.Color(255, 0, 0));

        btnUpdatePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdatePassword.setText("Update Account Information");
        btnUpdatePassword.setEnabled(false);
        btnUpdatePassword.setFocusable(false);
        btnUpdatePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePasswordActionPerformed(evt);
            }
        });

        btnEnableShowPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnableShowPassword.setText("Enable Show Password & Update Account Info");
        btnEnableShowPassword.setFocusable(false);
        btnEnableShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableShowPasswordActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Surname:");

        txtSurName.setEditable(false);
        txtSurName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout accountInformationLayout = new javax.swing.GroupLayout(accountInformation);
        accountInformation.setLayout(accountInformationLayout);
        accountInformationLayout.setHorizontalGroup(
            accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInformationLayout.createSequentialGroup()
                .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountInformationLayout.createSequentialGroup()
                        .addComponent(btnUpdatePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountInformationLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountInformationLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountInformationLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(accountInformationLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountInformationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountInformationLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountInformationLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtInfoPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowPassword, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(accountInformationLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnEnableShowPassword)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountInformationLayout.setVerticalGroup(
            accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountInformationLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSurName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInfoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btnEnableShowPassword)
                .addGap(18, 18, 18)
                .addGroup(accountInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnUpdatePassword))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Account Information", accountInformation);

        Support.setBackground(new java.awt.Color(255, 255, 255));

        btnGiveFeedBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGiveFeedBack.setText("Give Us FeedBack");
        btnGiveFeedBack.setFocusable(false);
        btnGiveFeedBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiveFeedBackActionPerformed(evt);
            }
        });

        btnApplyAsDriver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnApplyAsDriver.setText("Be a Rider");
        btnApplyAsDriver.setFocusable(false);
        btnApplyAsDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyAsDriverActionPerformed(evt);
            }
        });

        btnApplyAsMerchant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnApplyAsMerchant.setText("Become a Merchant");
        btnApplyAsMerchant.setFocusable(false);
        btnApplyAsMerchant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyAsMerchantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SupportLayout = new javax.swing.GroupLayout(Support);
        Support.setLayout(SupportLayout);
        SupportLayout.setHorizontalGroup(
            SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApplyAsMerchant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnApplyAsDriver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGiveFeedBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        SupportLayout.setVerticalGroup(
            SupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SupportLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(btnGiveFeedBack)
                .addGap(18, 18, 18)
                .addComponent(btnApplyAsDriver)
                .addGap(18, 18, 18)
                .addComponent(btnApplyAsMerchant)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Support", Support);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Setting's Page");

        javax.swing.GroupLayout blackLayout = new javax.swing.GroupLayout(black);
        black.setLayout(blackLayout);
        blackLayout.setHorizontalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        blackLayout.setVerticalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(black, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(black, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:

        this.dispose();
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPasswordActionPerformed
        // TODO add your handling code here:
        char echoChar = txtPassword.getEchoChar();

        
        if (echoChar == '*') {
            
            txtPassword.setEchoChar((char) 0);
        } else {
        
        txtPassword.setEchoChar('*');
        }
        
        if(!btnShowPassword.isSelected()) {
            btnShowPassword.setEnabled(false);
        }
    }//GEN-LAST:event_btnShowPasswordActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        String newPassword = txtPassword.getText();

        if (newPassword.length() >= 8) {
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, user, pass);

            String query = "UPDATE account SET password = ?, firstname = ?, surname = ? WHERE phonenumber = ?";
            PreparedStatement statement = connection.prepareStatement(query);

            statement.setString(1, hashPassword(newPassword));
            statement.setString(2, firstname);
            statement.setString(3, surname);
            statement.setString(4, phoneNumber);

            int rowsUpdated = statement.executeUpdate();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Account successfully updated.");
                txtPassword.setEditable(false);
                setPassword(newPassword);
                btnUpdatePassword.setEnabled(false);
                firstname=txtFirstName.getText();
                surname=txtSurName.getText();
                btnUpdate.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Failed to update. Account may not exist.");
            }

            statement.close();
            connection.close();
            } catch (ClassNotFoundException | SQLException e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password should be atleast 8 characters");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        
        
        if(txtPassword.getText().length() < 8) {
            txtInfoPassword.setText("Password should be at least 8 characters long");
            condition=false;
        } else {
            txtInfoPassword.setText("");
            condition=true;
        }
        
        
        if(!txtPassword.getText().equals(password)) {
            btnUpdate.setEnabled(true);
        } else if(txtFirstName.getText().equals(password)) {
            btnUpdate.setEnabled(false);
        }
        


    }//GEN-LAST:event_txtPasswordKeyReleased

    private void btnUpdatePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePasswordActionPerformed
        // TODO add your handling code here:
        btnUpdate.setEnabled(true);
        txtPassword.setEditable(true); 
        txtFirstName.setEditable(true);
        txtSurName.setEditable(true);
    }//GEN-LAST:event_btnUpdatePasswordActionPerformed

    private void btnGiveFeedBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiveFeedBackActionPerformed
        // TODO add your handling code here:
        try {
        
        String  feedback = JOptionPane.showInputDialog("Give us your feedback");
        if(feedback.length() >= 1) {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(url, user, pass);


                String query = "INSERT INTO feedback (fullname,phonenumber,message) VALUES (?, ?, ?)";
                PreparedStatement statement = connection.prepareStatement(query);



                statement.setString(1, firstname + " " + surname);
                statement.setString(2, phoneNumber);
                statement.setString(3, feedback);


                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(null, "Thanks for your feedback!");
                }

                statement.close();
                connection.close();
            } catch (ClassNotFoundException | SQLException e) {
            }
        }

        
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGiveFeedBackActionPerformed

    private void btnEnableShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableShowPasswordActionPerformed
        // TODO add your handling code here:
        try {
        String passwordConfirmation = JOptionPane.showInputDialog("Enter Your Password");
        if(passwordConfirmation.equals(password)) {
            btnShowPassword.setEnabled(true);
            btnUpdatePassword.setEnabled(true);
        } else if (!passwordConfirmation.equals(password)) {
            JOptionPane.showMessageDialog(null,"Incorrect Password");
        }
        
        }catch(Exception e) {
        }
    }//GEN-LAST:event_btnEnableShowPasswordActionPerformed

    private void btnApplyAsDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyAsDriverActionPerformed
        // TODO add your handling code here:

        this.dispose();
        SignUpDriverPage signUpDriverPage = new SignUpDriverPage();
        signUpDriverPage.SetAccount(phoneNumber, firstname, surname, password);
        signUpDriverPage.setVisible(true);
        
    }//GEN-LAST:event_btnApplyAsDriverActionPerformed

    private void btnApplyAsMerchantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyAsMerchantActionPerformed
        // TODO add your handling code here:

        this.dispose();
        SignUpMerchantPage signUpMerchantPage = new SignUpMerchantPage();
        signUpMerchantPage.SetAccount(phoneNumber, firstname, surname, password);
        signUpMerchantPage.setVisible(true);

    }//GEN-LAST:event_btnApplyAsMerchantActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
            this.dispose();

        if("driver".equals(role)) {
            DriverHomePage driverHomePage = new DriverHomePage();
            driverHomePage.SetAccount(phoneNumber, firstname, surname, password, role);
            driverHomePage.DisplayFullName(firstname, surname);
            driverHomePage.setVisible(true);
        } else if ("merchant".equals(role)) {
            MerchantHomePage merchantHomePage = new MerchantHomePage();
            merchantHomePage.SetAccount(phoneNumber, firstname, surname, password, role);
            merchantHomePage.DisplayFullName(firstname, surname);
            merchantHomePage.setVisible(true);
        } else {
            UserHomePage userHomePage = new UserHomePage();
            userHomePage.SetAccount(phoneNumber, firstname, surname, password);
            userHomePage.DisplayFullName(firstname, surname);
            userHomePage.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Support;
    private javax.swing.JPanel accountInformation;
    private javax.swing.JPanel black;
    private javax.swing.JButton btnApplyAsDriver;
    private javax.swing.JButton btnApplyAsMerchant;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnableShowPassword;
    private javax.swing.JButton btnGiveFeedBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JRadioButton btnShowPassword;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdatePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel settings;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JLabel txtInfoPassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSurName;
    // End of variables declaration//GEN-END:variables
}
