/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bite_Ride;

import io.github.cdimascio.dotenv.Dotenv;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author job Parado
 */
public class UserConfirmBooking extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmBooking
     */
    public UserConfirmBooking() {
        initComponents();
    }
    
    private String phoneNumber,firstname,surname,password;
    private String vehicle,pickUp,dropOff;
    private int transportationCost;
    private String generatedID;
    // one setter for account
    
    Dotenv dotenv = Dotenv.load();
    String url = dotenv.get("Database_URL");
    String user = dotenv.get("Admin_Name");
    String pass = dotenv.get("Admin_Password");

    
    public void SetAccount(String phoneNumber,String firstname , String surname,String password,int cost) {
        this.phoneNumber=phoneNumber;
        this.firstname=firstname;
        this.surname=surname;
        this.password=password;
        this.transportationCost=cost;
    }
    public void SetCost(String vehicle) {
        if(vehicle.equals("MotoDash")) {
            transportationCost+=20;
        } else if(vehicle.equals("CarDash")) {
            transportationCost+=60;
        }
    }
    public void setBooking(String vehicle,String pickUp,String dropOff) {
        this.vehicle = vehicle;
        this.pickUp=pickUp;
        this.dropOff=dropOff;
    }
    public void setText() {
        txtVehicle.setText(vehicle);
        txtDropOff.setText(dropOff);
        txtPickUp.setText(pickUp);
        
        
        
        txtTransportationCost.setText(Integer.toString(transportationCost));
    }
    
    
    public void giveUsFeedBack(String feedback) {
        try {
            if (feedback.length() >= 1) {
                Class.forName("com.mysql.cj.jdbc.Driver");
    
                try (Connection connection = DriverManager.getConnection(url, user, pass)) {
                    String query = "INSERT INTO feedback (fullname, phonenumber, message) VALUES (?, ?, ?)";
                    try (PreparedStatement statement = connection.prepareStatement(query)) {
                        statement.setString(1, firstname + " " + surname);
                        statement.setString(2, phoneNumber);
                        statement.setString(3, feedback);
    
                        int rowsInserted = statement.executeUpdate();
                        if (rowsInserted > 0) {
                            JOptionPane.showMessageDialog(null, "Thanks for your feedback!");
                        }
                    }
                } catch (SQLException e) {
                }
            }
        } catch (Exception e) {
        }
    }
    
    public void generatedID() {

        Random random = new Random();
        int num1 = random.nextInt(10);
        int num2 = random.nextInt(10);
        int num3 = random.nextInt(10);
        int num4 = random.nextInt(10);
        int num5 = random.nextInt(10);
        int num6 = random.nextInt(10);

        String generated= num1 + "" + num2 + "" + num3 + "" + num4 + "" + num5 + "" + num6;
        generatedID=generated;
    }
    
    public void insertBookingToDataBase() {
        try (Connection connection = DriverManager.getConnection(url, user,pass)) {
            String query = "INSERT INTO booking (userfullname, userphonenumber, pickuplocation, dropofflocation, orderfood, cost, vehicle, bookingid) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement statement = connection.prepareStatement(query)) {
                statement.setString(1, firstname + " " + surname);
                statement.setString(2, phoneNumber);
                statement.setString(3, pickUp);
                statement.setString(4, dropOff);
                statement.setString(5, "no");
                statement.setString(6, Integer.toString(transportationCost));
                statement.setString(7, vehicle);
                statement.setString(8, generatedID);
                    
                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConfirmBookingTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnConfirmBooking = new javax.swing.JButton();
        txtPickUp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDropOff = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtVehicle = new javax.swing.JTextField();
        btnCancel1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDropOff1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTransportationCost = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirm Your Booking");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        ConfirmBookingTab.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pickup Location");

        btnConfirmBooking.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmBooking.setText("Confirm Booking");
        btnConfirmBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmBookingActionPerformed(evt);
            }
        });

        txtPickUp.setEditable(false);
        txtPickUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dropoff Location");

        txtDropOff.setEditable(false);
        txtDropOff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mode of Transportation");

        txtVehicle.setEditable(false);
        txtVehicle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnCancel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel1.setText("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Payment Method:");

        txtDropOff1.setEditable(false);
        txtDropOff1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDropOff1.setText("Cash On Delivery");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Transportation:");

        txtTransportationCost.setEditable(false);
        txtTransportationCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTransportationCost.setText("Cost");

        javax.swing.GroupLayout ConfirmBookingTabLayout = new javax.swing.GroupLayout(ConfirmBookingTab);
        ConfirmBookingTab.setLayout(ConfirmBookingTabLayout);
        ConfirmBookingTabLayout.setHorizontalGroup(
            ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmBookingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmBookingTabLayout.createSequentialGroup()
                        .addComponent(btnCancel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(btnConfirmBooking))
                    .addComponent(txtPickUp)
                    .addComponent(txtDropOff)
                    .addComponent(txtVehicle)
                    .addGroup(ConfirmBookingTabLayout.createSequentialGroup()
                        .addGroup(ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(ConfirmBookingTabLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDropOff1))
                            .addGroup(ConfirmBookingTabLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTransportationCost, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ConfirmBookingTabLayout.setVerticalGroup(
            ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmBookingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPickUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDropOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDropOff1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTransportationCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(ConfirmBookingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmBooking)
                    .addComponent(btnCancel1))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirm Your Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmBookingTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ConfirmBookingTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
        // TODO add your handling code here:
        int confirmation = JOptionPane.showConfirmDialog(null,"Confirm Booking ?");


        if(confirmation == 0) {
            generatedID();
            insertBookingToDataBase();
            
            try {
                String  feedback = JOptionPane.showInputDialog("Order Submitted Consider Giving us Feedback ?");
                giveUsFeedBack(feedback);
            } catch (Exception e) {
            }
            
            this.dispose();
            UserHomePage userHomePage = new UserHomePage();
            userHomePage.SetAccount(phoneNumber, firstname, surname, password);
            userHomePage.DisplayFullName(firstname, surname);
            userHomePage.setVisible(true);  
        }
    }//GEN-LAST:event_btnConfirmBookingActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        UserHomePage userHomePage = new UserHomePage();
        userHomePage.SetAccount(phoneNumber, firstname, surname, password);
        userHomePage.DisplayFullName(firstname, surname);
        userHomePage.setVisible(true);
    }//GEN-LAST:event_btnCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserConfirmBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConfirmBookingTab;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDropOff;
    private javax.swing.JTextField txtDropOff1;
    private javax.swing.JTextField txtPickUp;
    private javax.swing.JTextField txtTransportationCost;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}
