/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bite_Ride;

/**
 *
 * @author job Parado
 */
public class UserSetLocation extends javax.swing.JFrame {

    /**
     * Creates new form UserSetLocation
     */
    public UserSetLocation() {
        initComponents();
        
        
    }
    boolean condition;

    private String vehicle,pickUp,dropOff;
    private String phoneNumber,firstname,surname,password;

    // one setter for account

    
    public void SetAccount(String phoneNumber,String firstname , String surname,String password) {
        this.phoneNumber=phoneNumber;
        this.firstname=firstname;
        this.surname=surname;
        this.password=password;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        black = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        cmbPickUp = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDropOff = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        btnMotoDash = new javax.swing.JRadioButton();
        btnCarDash = new javax.swing.JRadioButton();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Set Your Location");
        setFocusable(false);
        setResizable(false);

        black.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setText("Check Booking");
        btnNext.setEnabled(false);
        btnNext.setFocusable(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setFocusable(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cmbPickUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbPickUp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select location", "Tunasan", "Sucat", "Buli", "Putatan", "Bayanan", "Alabang", "Poblacion", "Ayala alabang", "Cupang" }));
        cmbPickUp.setFocusable(false);
        cmbPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPickUpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PickUp Location:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Dropoff Location:");

        cmbDropOff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbDropOff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select location", "Tunasan", "Sucat", "Buli", "Putatan", "Bayanan", "Alabang", "Poblacion", "Ayala alabang", "Cupang" }));
        cmbDropOff.setFocusable(false);
        cmbDropOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDropOffActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Select Your Mode Of Transportation:");

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/motodash.jpg"))); // NOI18N

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cardash.jpg"))); // NOI18N

        btnMotoDash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMotoDash.setText("MotoDash");
        btnMotoDash.setContentAreaFilled(false);
        btnMotoDash.setFocusable(false);
        btnMotoDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoDashActionPerformed(evt);
            }
        });

        btnCarDash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCarDash.setText("CarDash");
        btnCarDash.setContentAreaFilled(false);
        btnCarDash.setFocusable(false);
        btnCarDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarDashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMotoDash, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCarDash)
                            .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addComponent(cmbPickUp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbDropOff, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMotoDash)
                    .addComponent(btnCarDash))
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPickUp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDropOff, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnNext))
                .addContainerGap())
        );

        jlabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(255, 255, 255));
        jlabel3.setText("And Your Pickup & Dropoff Location");

        jlabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(255, 255, 255));
        jlabel4.setText("Setup Your Mode Of Transportation");

        javax.swing.GroupLayout blackLayout = new javax.swing.GroupLayout(black);
        black.setLayout(blackLayout);
        blackLayout.setHorizontalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blackLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel3)
                    .addComponent(jlabel4))
                .addGap(21, 21, 21))
        );
        blackLayout.setVerticalGroup(
            blackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blackLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlabel4)
                .addGap(18, 18, 18)
                .addComponent(jlabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(black, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(black, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:

        this.dispose();
        UserHomePage userHomePage = new UserHomePage();
        userHomePage.SetAccount(phoneNumber, firstname, surname, password);
        userHomePage.DisplayFullName(firstname, surname);
        userHomePage.setVisible(true);


    }//GEN-LAST:event_btnCancelActionPerformed

    private void cmbPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPickUpActionPerformed
        // TODO add your handling code here:

        if(cmbPickUp.getSelectedItem().toString() != "Please select location") {
            pickUp=cmbPickUp.getSelectedItem().toString();
        }

        if(cmbPickUp.getSelectedItem().toString() != "Please select location" && cmbDropOff.getSelectedItem().toString() != "Please select location") {
            if(cmbPickUp.getSelectedItem().toString() != cmbDropOff.getSelectedItem().toString()) {
                if (condition) {
                    btnNext.setEnabled(true);
                }
            }
        }
        
        if (cmbDropOff.getSelectedItem().toString() == cmbPickUp.getSelectedItem().toString()) {
            btnNext.setEnabled(false);
        } 

    }//GEN-LAST:event_cmbPickUpActionPerformed

    private void cmbDropOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDropOffActionPerformed
        // TODO add your handling code here:

        if(cmbDropOff.getSelectedItem().toString() != "Please select location") {
            dropOff=cmbDropOff.getSelectedItem().toString();
        }

        if(cmbPickUp.getSelectedItem().toString() != "Please select location" && cmbDropOff.getSelectedItem().toString() != "Please select location") {
            if(cmbPickUp.getSelectedItem().toString() != cmbDropOff.getSelectedItem().toString()) {
                if (condition) {
                    btnNext.setEnabled(true);
                }
            }
        }

        if (cmbDropOff.getSelectedItem().toString() == cmbPickUp.getSelectedItem().toString()) {
            btnNext.setEnabled(false);
        }

    }//GEN-LAST:event_cmbDropOffActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        int transportationCost = 0;
        
        switch (pickUp) {

        case "Tunasan":
            switch (dropOff) {
                case "Sucat":
                case "Buli":
                case "Ayala alabang":
                case "Cupang":
                    transportationCost = 100;
                    break;
                case "Putatan":
                case "Bayanan":
                case "Alabang":
                case "Poblacion":
                    transportationCost = 70;
                    break;
            }
            break;

        case "Sucat":
            switch (dropOff) {
                case "Tunasan":
                case "Poblacion":
                case "Ayala alabang":
                    transportationCost = 100;
                    break;
                case "Buli":
                case "Putatan":
                case "Bayanan":
                case "Alabang":
                case "Cupang":
                    transportationCost = 70;
                    break;
            }
            break;

        case "Buli":
            switch (dropOff) {
                case "Tunasan":
                case "Poblacion":
                    transportationCost = 100;
                    break;
                case "Sucat":
                case "Putatan":
                case "Bayanan":
                case "Alabang":
                case "Ayala alabang":
                case "Cupang":
                    transportationCost = 70;
                    break;
            }
            break;

        case "Putatan":
            switch (dropOff) {
                case "Ayala alabang":
                    transportationCost = 100;
                    break;
                default:
                    transportationCost = 70;
            }
            break;

        case "Bayanan":
            switch (dropOff) {
                case "Sucat":
                case "Ayala alabang":
                case "Cupang":
                    transportationCost = 100;
                    break;
                case "Tunasan":
                case "Buli":
                case "Putatan":
                case "Alabang":
                case "Poblacion":
                    transportationCost = 70;
                    break;
            }
            break;

        case "Alabang":
            transportationCost = 70;
            break;

        case "Poblacion":
            switch (dropOff) {
                case "Sucat":
                case "Buli":
                case "Cupang":
                    transportationCost = 100;
                    break;
                case "Tunasan":
                case "Putatan":
                case "Bayanan":
                case "Alabang":
                case "Ayala alabang":
                    transportationCost = 70;
                    break;
            }
            break;

        case "Ayala alabang":
            switch (dropOff) {
                case "Tunasan":
                case "Sucat":
                case "Putatan":
                case "Bayanan":
                    transportationCost = 100;
                    break;
                case "Buli":
                case "Alabang":
                case "Poblacion":
                case "Cupang":
                    transportationCost = 70;
                    break;
            }
            break;

        case "Cupang":
            switch (dropOff) {
                case "Tunasan":
                case "Bayanan":
                case "Poblacion":
                    transportationCost = 100;
                    break;
                case "Sucat":
                case "Buli":
                case "Putatan":
                case "Alabang":
                case "Ayala alabang":
                    transportationCost = 70;
                    break;
            }
            break;
    }

        
        this.dispose();
        UserConfirmBooking userConfirmBooking = new UserConfirmBooking();
        userConfirmBooking.SetAccount(phoneNumber, firstname, surname, password, transportationCost);
        userConfirmBooking.SetCost(vehicle);
        userConfirmBooking.setBooking(vehicle, pickUp, dropOff);
        userConfirmBooking.setText();
        userConfirmBooking.setVisible(true);

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnMotoDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoDashActionPerformed
        // TODO add your handling code here:

        btnCarDash.setSelected(false);
        vehicle="MotoDash";
        condition=true;
        if(!btnMotoDash.isSelected()) {
            vehicle="";
            condition=false;
        }

        if(cmbPickUp.getSelectedItem().toString() != "Please select location" && cmbDropOff.getSelectedItem().toString() != "Please select location") {
            if(cmbPickUp.getSelectedItem().toString() != cmbDropOff.getSelectedItem().toString()) {
                if (condition) {
                    btnNext.setEnabled(true);
                }
            }
        }

        if (cmbDropOff.getSelectedItem().toString() == cmbPickUp.getSelectedItem().toString()) {
            btnNext.setEnabled(false);
        }
        if(!condition) {
            btnNext.setEnabled(false);
        }

    }//GEN-LAST:event_btnMotoDashActionPerformed

    private void btnCarDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarDashActionPerformed
        // TODO add your handling code here:

        btnMotoDash.setSelected(false);
        vehicle="CarDash";
        condition=true;
        if(!btnCarDash.isSelected()) {
            vehicle="";
            condition=false;
        }

        if(cmbPickUp.getSelectedItem().toString() != "Please select location" && cmbDropOff.getSelectedItem().toString() != "Please select location") {
            if(cmbPickUp.getSelectedItem().toString() != cmbDropOff.getSelectedItem().toString()) {
                if (condition) {
                    btnNext.setEnabled(true);
                }
            }
        }

        if (cmbDropOff.getSelectedItem().toString() == cmbPickUp.getSelectedItem().toString()) {
            btnNext.setEnabled(false);
        }
        if(!condition) {
            btnNext.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnCarDashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSetLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSetLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSetLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSetLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSetLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel black;
    private javax.swing.JButton btnCancel;
    private javax.swing.JRadioButton btnCarDash;
    private javax.swing.JRadioButton btnMotoDash;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox<String> cmbDropOff;
    private javax.swing.JComboBox<String> cmbPickUp;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    // End of variables declaration//GEN-END:variables
}
